#!/global/software/python-2.7.2/bin/python
from __future__ import with_statement

import sys
import os
import subprocess
import shutil
import argparse
import ConfigParser
import stat
import time
import ligprep
import glob

import numpy as np

class PrepVSConfigError(Exception):
    pass

class PrepVSConfig(object):

    def __init__(self, args):

        # check if config file exist
        if not os.path.exists(args.config_file):
            raise PrepVSConfigError("Config file %s not found!"%(args.config_file))

        config = ConfigParser.SafeConfigParser()
        config.read(args.config_file)

        self.input_file_l = []
        if args.input_file_l:
            for file_l in args.input_file_l:
                # check if ligand file exists
                if not os.path.exists(file_l):
                    raise PrepVSConfigError("File %s not found!"%(self.input_file_l))
                self.input_file_l.append(os.path.abspath(file_l))
        self.nfiles_l = len(self.input_file_l)

        self.input_file_r = []
        if args.input_file_r:
            for file_r in args.input_file_r:
                # check if ligand file exists
                if not os.path.exists(file_r):
                    raise PrepVSConfigError("File %s not found!"%(self.input_file_r))
                self.input_file_r.append(os.path.abspath(file_r))
        self.nfiles_r = len(self.input_file_r)

        self.make = args.make

        self.single = args.single
        if self.single and not self.make:
            raise ValueError("option single should be used together with option make")

        self.set_ligprep_options(config)
        self.set_sitefind_options(config, args)

    def set_ligprep_options(self, config):
        """set ligprep options"""

        section = 'LIGPREP'
        self.ligprep = {}
        # set ligprep defaults options if they are not mentionned in the config file
        for key, value in ligprep.ligprep_default_options.items():
            if key not in self.ligprep:
                self.ligprep[key] = value
        # check config file (would possibly default preset parameters)
        if config.has_section(section):
            self.ligprep = dict(config.items(section))

    def set_sitefind_options(self, config, args):
        """set options for the binding site"""

        known_sitefind_programs = ['moe']

        self.site = {}
        if args.blind:
            section = 'SITEFINDER'
            if config.has_section(section):
                if not config.has_option(section, 'program'):
                    raise PrepVSConfigError("Option program in section %s is required in config file for local docking!"%section)
                if config.get(section, 'program').lower() not in known_sitefind_programs:
                    raise PrepVSConfigError("Option program in section %s should be one of "%section + ", ".join(known_sitefind_programs))
                self.site['program'] = config.get(section, 'program')
                # set site finder default options if they are not mentionned in the config file
                program = self.site['program']
                __import__(program)
                default_settings = getattr(sys.modules[program], 'default_sitefind_settings')
                for key, value in default_settings.iteritems():
                    self.site[key] = value
                # check config file (would possibly default preset parameters)
                config_c = dict(config.items(section))
                for key, value in config_c.iteritems():
                    self.site[key] = value
            else:
                raise PrepVSConfigError("Section %s is required in config file for blind docking!"%section)

class PrepVS(object):

    def create_arg_parser(self):

        parser = argparse.ArgumentParser(description="Prepare files for virtual screening")

        parser.add_argument('-l',
            type=str,
            dest='input_file_l',
            required=True,
            nargs='+',
            help = 'Ligand coordinate file(s): .pdb, .sdf, .smi')

        parser.add_argument('-r',
            type=str,
            dest='input_file_r',
            required = True,
            nargs='+',
            help = 'Receptor coordinate file(s): .pdb')

        parser.add_argument('-f',
            dest='config_file',
            required=True,
            help='config file: .ini')

        parser.add_argument('--blind',
            dest='blind',
            action='store_true',
            default=False,
            help='Find possible binding sites (blind docking)')

        parser.add_argument('--make',
            dest='make',
            action='store_true',
            default=False,
            help='Create directories for each ligand/target/isomer triplet')

        parser.add_argument('--single',
            dest='single',
            action='store_true',
            default=False,
            help='Create directory even when single ligands or receptors are involved (should be used together with --make)')

        return parser

    def prepare_vs(self, config, args):

        #for ligdir in glob.glob('ligprep*'):
        #    shutil.rmtree(ligdir)

        #for recdir in glob.glob('recprep*'):
        #    shutil.rmtree(recdir)

        ## prepare structures
        #self.prepare_structures(config, args)

        # (A) LIGAND level
        for idx in range(config.nfiles_l):
            if config.nfiles_l == 1 and not config.single:
                ligdir = '.'
            else:
                ligdir = 'lig' + str(idx)
                if os.path.isdir(ligdir):
                    shutil.rmtree(ligdir)
                os.mkdir(ligdir)

            # (B) RECEPTOR level
            for jdx in range(config.nfiles_r):
                recdir = ligdir
                if config.nfiles_r == 1 and not config.single:
                    recdir += '/.'
                else:
                    recdir += '/rec' + str(jdx)
                    if os.path.isdir(recdir):
                        shutil.rmtree(recdir)
                    os.mkdir(recdir)

                # (C) ISOMER level
                ligpdir = 'ligprep' + str(idx)
                recpdir = 'recprep' + str(jdx)
                recfile = glob.glob(recpdir+'/*.prep.pdb')
                assert len(recfile) == 1, "length of recfile list different from 1!"
                recfile = recfile[0]

                for ligfile in sorted(glob.glob(ligpdir+'/*.prep_*.sdf')):
                    suffix = os.path.splitext(ligfile)[0]
                    kdx = suffix.split('_')[-1]
                    isodir = recdir + '/isomer' + kdx
                    if os.path.isdir(isodir):
                        shutil.rmtree(isodir)
                    os.mkdir(isodir)
                    if args.blind:
                        table = np.loadtxt(recpdir+'/sitefinder.log')
                        if len(table.shape) == 1:
                            table = table[np.newaxis,:]
                        for line in table:
                            ldx = int(line[0])
                            # TODO: include the size of the ligand to compute boxsize
                            new_config_file = isodir + '/config.' + str(ldx) + '.ini'
                            self.update_site_config_file(new_config_file, args.config_file, line[2:5], 2*line[5])
                    else:
                        # copy the config file in the directory
                        shutil.copyfile(args.config_file, isodir + '/config.ini')

                    # copy the files for ligand and receptor in the corresponding dir
                    shutil.copyfile(ligfile, isodir + '/lig.sdf')
                    shutil.copyfile(recfile, isodir +'/rec.pdb')

    def prepare_structures(self, config, args):

        curdir = os.getcwd()
        print "Preparing ligands..."
        for idx, file_l in enumerate(config.input_file_l):
            ligpdir = 'ligprep' + str(idx)
            if os.path.isdir(ligpdir):
                shutil.rmtree(ligpdir)
            os.mkdir(ligpdir)
            os.chdir(ligpdir)
            ligprep.prepare_ligand(file_l, config)
            os.chdir(curdir)

        print "Preparing receptors..."
        for idx, file_r in enumerate(config.input_file_r):
            recpdir = 'recprep' + str(idx)
            if os.path.isdir(recpdir):
                shutil.rmtree(recpdir)
            os.mkdir(recpdir)
            os.chdir(recpdir)
            new_file_r = ligprep.prepare_receptor(file_r, config)
            if args.blind:
                self.find_binding_sites(new_file_r, config)
            os.chdir(curdir)

    def update_site_config_file(self, new_config_file, config_file, center, boxsize):

        shutil.copyfile(config_file, new_config_file)

        tmp_config_file = list(os.path.splitext(new_config_file))
        tmp_config_file.insert(1,'_tmp')
        tmp_config_file = ''.join(tmp_config_file)

        # remove section 'SITE' of config file if exists
        with open(tmp_config_file, 'w') as tmpf:
            with open(new_config_file, 'r') as newf:
                sitesection = False
                for line in newf:
                    if line.startswith('[SITE]'):
                        sitesection = True
                    if sitesection:
                        if line.startswith('[') and not line.startswith('[SITE]'): # if reach new section
                            sitesection = False
                    if not sitesection:
                        tmpf.write(line)

        shutil.move(tmp_config_file, new_config_file)

        # add new section 'SITE'
        center_conf = ', '.join(map(str, center.tolist()))
        boxsize_conf = ', '.join(map(str, [boxsize for idx in range(3)]))
        newsite_section = """
[SITE]
center = %(center_conf)s
boxsize = %(boxsize_conf)s"""% locals()

        with open(new_config_file, 'a') as newf:
            newf.write(newsite_section)

    def find_binding_sites(self, pdbfile, config):

        program = config.site['program']

        # (A) write script
        script_name = 'find_binding_sites.sh'
        write_sitefinder_script = getattr(sys.modules[program], 'write_sitefinder_script')
        write_sitefinder_script(script_name, pdbfile, config)
        os.chmod(script_name, stat.S_IRUSR | stat.S_IWUSR | stat.S_IRGRP | stat.S_IROTH | stat.S_IXUSR)

        # (B) execute script
        subprocess.check_call("./" + script_name + " &> sitefinder.log", shell=True, executable='/bin/bash')

    def run(self):

        parser = self.create_arg_parser()
        args = parser.parse_args()

        tcpu1 = time.time()
        config = PrepVSConfig(args)

        # prepare virtual screening
        self.prepare_vs(config, args)
        tcpu2 = time.time()

if __name__ == '__main__':
    PrepVS().run()
